name: Github deploy scp
author: dj256
description: Github Action to deploy code on a remote server via scp
inputs:
  local:
    description: "Path to the local file or folder"
    required: true
  remote:
    description: "Path to the remote folder"
    required: true
  dotfiles:
    description: "Determines if files with a leading dot (.) on folder copy is included"
    required: false
    default: false
  host:
    description: "Hostname or IP address of the server"
    required: true
  username:
    description: "Username for authentication."
    required: false
  port:
    description: "Port number of the server"
    required: false
    default: "22"
  password:
    description: "Password for password-based user authentication."
    required: false
  exclude:
    description: "Paths excluded from the copy (relative to remote path)"
    required: false
    default: ''
runs:
  using: "node12"
  main: "out/main.js"
branding:
  color: "purple"
  icon: "copy"
