name: Github deploy scp
author: dj256
description: Github Action to deploy code on a remote server via scp
inputs:
  local:
    description: "Path to the local file or folder"
    required: true
  remote:
    description: "Path to the remote folder"
    required: true
  host:
    description: "Hostname or IP address of the server"
    required: true
  username:
    description: "Username for authentication."
    required: false
  password:
    description: "Password for authentication."
    required: false
  port:
    description: "Port of the server to connect to"
    required: false
    default: "22"
  exclude:
    description: "Paths excluded from the copy (relative to remote path)"
    required: false
    default: ''
  dotfiles:
    description: "Determines if files with a leading dot (.) on folder copy is included"
    required: false
    default: false
  rmRemote:
    description: "Whether or not to erase all content in the remote directory before copy. Note that file having the
    same name will still be erased even if you set this option to false"
    required: false
    default: true
runs:
  using: "node12"
  main: "out/main.js"
branding:
  color: "purple"
  icon: "copy"
