name: test-deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup demo
        run: |
          touch file{1..3}.txt
          touch file{1..3}.js
          mkdir dir1
          touch dir1/file1{1..3}.txt
          touch dir1/file1{1..3}.js
      - name: Copy file
        uses: ./
        with:
          local: ./file1
          remote: /scp
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
      - name: Copy directory
        uses: ./
        with:
          local: ./dir1
          remote: /scp
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
      - name: Copy files with simple glob path
        uses: ./
        with:
          local: '*.js'
          remote: /scp
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
      - name: Copy files with globstar
        uses: ./
        with:
          local: '**/*.js'
          remote: /scp
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
      - name: Copy excluding js files
        uses: ./
        with:
          local: 'dir1'
          remote: /scp
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          exclude: '*.js'
      - name: Copy excluding dir1
        uses: ./
        with:
          local: ''
          remote: /scp
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          exclude: 'dir1'
      - name: Copy excluding dir1/file11.txt
        uses: ./
        with:
          local: ''
          remote: /scp
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          exclude: 'dir1/file11.txt'
